# Generated by Django 4.2.16 on 2024-11-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleHostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True)),
                ('os_version', models.CharField(max_length=32, null=True)),
                ('python3_version', models.CharField(max_length=32, null=True)),
                ('status_notes', models.CharField(max_length=256, null=True)),
                ('virtual_disk_size_mb', models.IntegerField(null=True)),
                ('special_notes', models.CharField(max_length=64, null=True)),
                ('running', models.BooleanField(default=False, null=True)),
                ('cyteen_vm_cpu_allocation', models.IntegerField(null=True)),
                ('cyteen_vm_ram_allocation', models.IntegerField(null=True)),
                ('r720_vm_cpu_allocation', models.IntegerField(null=True)),
                ('r720_vm_ram_allocation', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ansible_host_summary',
            },
        ),
    ]
