# Generated by Django 5.1.3 on 2025-01-30 22:43

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeavyHitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField()),
                ('tmstamp', models.DateField()),
                ('cidrBlock', netfields.fields.CidrAddressField(max_length=43)),
                ('rule_num', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('blocked_ports', models.IntegerField()),
                ('bh_id', models.BigIntegerField()),
                ('blackhole', netfields.fields.CidrAddressField(max_length=43)),
            ],
            options={
                'db_table': 'heavy_hitters',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='blacklist',
            new_name='Blackhole',
        ),
    ]
