# Generated by Django 5.1.3 on 2025-01-29 23:27

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_heavyhitters'),
    ]

    operations = [
        migrations.CreateModel(
            name='heavyHitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField()),
                ('tmstamp', models.DateTimeField()),
                ('cidrBlock', netfields.fields.CidrAddressField(max_length=43)),
                ('rule_num', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('blocked_ports', models.IntegerField()),
                ('bh_id', models.BigIntegerField()),
                ('blackhole', netfields.fields.CidrAddressField(max_length=43)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='heavyHitters',
        ),
    ]
